<?php

define("t_send_to_customer","ส่งแขก");
define("t_customer_history","ประวัติส่งแขก");
define("t_job_received","งานรับ-ส่ง");
define("t_tour_booking","จองทัวร์");
define("t_receipts","รายรับ");
define("t_expenses","รายจ่าย");
define("t_my_account","บัญชีของฉัน");
define("t_help_tools","เครื่องมือช่วยเหลือ");
define("t_all_jobs","งานทั้งหมด");
define("t_transfer_record","โอนเงิน-แจ้งโอน");
define("t_province_you","คุณอยู่จังหวัด");
define("t_friends","แนะนำเพื่อน");
define("t_maps","แผนที่");
define("t_login_phuket","ล็อกอินจังหวัดที่คุณอยู่ ");
define("t_login_another_province","ล็อกอินจังหวัดอื่น");
define("t_shopping","ช้อปปิ้ง");
define("t_provinces","จังหวัดอื่น");
define("t_guest_shopping","แขกช็อปปิ้ง");
define("t_customer","แขกรับส่ง");
define("t_yesterday","เมื่อวาน");
define("t_today","วันที่");
define("t_no_guest_list","ไม่มีรายการส่งแขก");
define("t_pick_up_place","สถานที่รับ");
define("t_agents","เอเย่นต์");
define("t_private","ไพรเวท");
define("t_exports","ส่งออก");
define("t_customer_name","ชื่อแขก");
define("t_phone","โทรศัพท์");
define("t_voucher_number","วอเชอร์");
define("t_drop_place","สถานที่ส่ง");
define("t_type_of_vehicle","ประเภทรถ");
define("t_arrive_drop_place","ถึงสถานที่ส่งแขก");
define("t_check_customer_name","เช็คชื่อแขก");
define("t_check_vehicle","งานสำเร็จ | เช็ครถ");
define("t_check_luggage","ตรวจเช็คสัมภาระในรถ");
define("t_photo","ภาพ");
define("t_time_taking_photo","ถ่ายเมื่อ");
define("t_in_advance","ล่วงหน้า");
define("t_no_job","ไม่มีงาน");
define("t_now","ตอนนี้");
define("t_navigation","นำทาง");
define("t_details","รายละเอียด");
define("t_distance","ระยะทาง");
define("t_km","กม");
define("t_minutes","เวลา");
define("t_pay_deposit","นาที");
define("t_ok","ตกลง");
define("t_please_confirm_selection","โปรดยืนยันการเลือกงานของคุณ");
define("t__not","ไม่เเลือก");
define("t_select","เลือก");
define("t_jobs","งาน");
define("t_total","รวม");
define("t_total_expenses","รายจ่ายรวม");
define("t_balances","ยอดคงเหลือ");
define("t_transfers","โอนเงิน");
define("t_transfer_notice","แจ้งโอน");
define("t_transferred_account_details","รายละเอียดบัญชีรับโอน");
define("t_bank_name","ชื่อธนาคาร");
define("t_account_number","เลขที่บัญชี");
define("t_account_name","ชื่อบัญชี");
define("t_your_balance","ยอดเงินคงเหลือของคุณ");
define("t_transfer_details","รายละเอียดบัญชีรับโอน");
define("t_transfer_banks","ธนาคารที่โอน");
define("t_amount","จำนวนเงิน");
define("t_money_transfer_slip","อับโหลดสลิปโอนเงิน");
define("t_take_photos","ถ่ายภาพ");
define("t_cancel","ยกเลิก");
define("t_no_photo_available","ไม่มีภาพถ่าย");
define("t_unsubscribe","ยกเลิกส่งแขก");
define("t_booking_number","เลขจอง");
define("t_reservation _information","ข้อมูลการจอง");
define("t_car_driver_information","ข้อมูลรถและคนขับ");
define("t_check_in_information","ข้อมูลการเช็คอิน");
define("t_place_of_delivery","ถึงสถานที่ส่งแขก");
define("t_reception","พนักงานรับแขก");
define("t_income","รายได้");
define("t_parking fee","ค่าจอด + ค่าหัว");
define("t_nationality","สัญชาติ");
define("t_not_paid","ยังไม่จ่ายเงิน");
define("t_documents","เอกสาร");
define("t_bouns","ค่าหัว");
define("t_pay_cash","จ่ายเงินสด");
define("t_register","ลงทะเบียน");
define("t_per_person","รายรับต่อหัว");
define("t_time","เวลา"); 
define("t_home","หน้าหลัก"); 
define("t_pick_up_customer","รับแขก"); 


define("t_Welcome_t-share","ยินดีต้อนรับเข้าสู่ T-Share"); 
define("t_navigation_map","แสดงแผนที่นำทาง"); 
define("t_flight","เที่ยวบิน"); 
define("t_number","จำนวน"); 
define("t_customer_not_go","แขกไม่ไป"); 
define("t_customer_no_register","แขกลงทะเบียนไม่ได้"); 
define("t_wrong_selected_+place","เลือกสถานที่ผิด"); 
define("t_are_you_sure","คุณแน่ใจหรือไม่"); 
define("t_need_cancel_transfer","ว่าต้องการยกเลิกการส่งแขก"); 
define("t_want_confirm_payment","ว่าต้องการยืนยันการจ่ายเงิน"); 
define("t_upload_the_document_picture","กรุณาอัพโหลดเอกสารหรือภาพถ่าย"); 
define("t_success","สำเร็จ"); 
define("t_process","จัดการ"); 
define("t_amend","แก้ไข"); 
define("t_confirm","ยืนยัน"); 
define("t_delivery_time","เวลาส่ง"); 
define("t_number_customers","จำนวนแขก"); 
define("t_adult","ผู้ใหญ่"); 
define("t_child","เด็ก"); 
define("t_infant","ทารก"); 
define("t_edit_data","แก้ไขข้อมูล"); 
define("t_confirm_registration","ยืนยันการลงทะเบียน"); 
define("t_registration_failed","ลงทะเบียนไม่ได้"); 
define("t_work_history","ประวัติการจัดการงาน"); 
define("t_payment","ชำระเงิน"); 
define("t_status","สถานะ"); 
define("t_colleague","เพื่อนร่วมงาน"); 
define("t_today_job","งานวันนี้"); 
define("t_add_new_job","เพิ่มงานใหม่"); 
define("t_send","ส่ง"); 
define("t_remind","เตือน"); 
define("t_voice_dialing","โทรออกด้วยเสียง"); 
define("t_message","ข้อความ"); 
define("t_car_information","ข้อมูลรถ"); 
define("t_add_new_car","เพิ่มรถใหม่"); 
define("t_all_car","รถทั้งหมด"); 
define("t_income_details","บัญชีรายรับ"); 
define("t_receipt_of_parking_fee","รายรับ ค่าจอด ค่าหัว"); 
define("t_withdrawal_record","ประวัติการถอนเงิน"); 
define("t_bank_account","บัญชีธนาคาร"); 
define("t_personal_information","ข้อมูลส่วนตัว"); 
define("t_important_data_file","ข้อมูลและเอกสารสำคัญ"); 
define("t_change_profile_picture","เปลี่ยนภาพประจำตัว"); 
define("t_contact_information","ข้อมูลการติดต่อสื่อสาร"); 
define("t_phone_number_the","เบอร์โทรศัพท์ส่วนตัว"); 
define("t_change_password","เปลี่ยนรหัสผ่าน"); 
define("t_documents","ไฟล์เอกสาร"); 
define("t_work_information","ข้อมูลการทำงาน"); 
define("t_missed_meal_fee","ค่าเที่ยว เบี้ยเลี้ยง"); 
define("t_overtime_pay","เงินเดือน ค่าโอที"); 
define("t_phone_number","เบอร์โทรศัพท์"); 
define("t_driver_phone_no","เบอร์โทรศัพท์คนขับรถ"); 
define("t_helpdesk","โปรแกรมช่วยเหลือ"); 
define("t_find_hotel","ค้นหาโรงแรม"); 
define("t_check_flight","เช็คเที่ยวบิน"); 
define("t_language","ภาษา"); 
define("t_sign_out","ออกจากระบบ"); 
define("t_sign_out_successfully","ออกจากระบบสำเร็จ"); 
define("t_started_waiting_for_customer","แจ้งรอรับแขก"); 
define("t_go_with_king_power","ไปกับรถคิงส์ พาวเวอร์"); 
define("t_car_shifts","รอบส่งกลับ"); 
define("t_choose_car_shifts","เลือกรอบ"); 
define("t_send_back_location","ส่งกลับที่"); 
define("t_select_area","เลือกพื้นที่"); 
define("t_send_airport_shifts","รอบไปสนามบิน"); 
define("t_airport","สนามบิน"); 


define("t_user_information","ข้อมูลผู้ใช้งาน");
define("t_chat","แชท");
define("t_financial_accounting","บัญชี การเงิน");
define("t_add_colleague","เพิ่มเพื่อนร่วมงาน");
define("t_manage_car","จัดการรถ");
define("t_check_condition_car.","ตรวจเช็คสภาพรถ");
define("t_inform_car_repair","แจ้งซ่อมรถ");
define("t_service_and_insurance","ศูนย์บริการและประกันภัย");
define("t_new_applier","รายชื่อสมัครใหม่");
define("t_all_colleagues","เพื่อนร่วมงานทั้งหมด");
define("t_handle_task","จัดการงาน");
define("t_open_for_business","เปิดให้ บริการ");
define("t_everyday","ทุกวัน");
define("t_work_remuneration","ค่าตอบแทน");
define("t_look_work_remuneration","ดูค่าตอบแทน");
define("t_location","ตำแหน่งที่ตั้ง");
define("t_query","สอบถาม");
define("t_marketing","การตลาด");
define("t_download","ดาวน์โหลด");
define("t_bouchure","โบร์ชัวร์");
define("t_go_shopping","ไปช็อปปิ้ง");
define("t_out_of_service","ปิดให้บริการ");
define("t_select_region","เลือกภูมิภาค");
define("t_place","สถานที่");
define("t_select_province","เลือกจังหวัด");
define("t_remaining_time","เหลือเวลา");
define("t_send_to_shopping","ส่งแขกช็อปปิ้ง");
define("t_duty_free","ดิวตี้ฟรี");
define("t_all_transfer_job","งานส่งแขกทั้งหมด");
define("t_nearest_location","ต่ำแหน่งใกล้สุด");
define("t_price","	ราคา");
define("t_acept_order","รับงาน");
define("t_all_transfer_job","งานส่งแขกทั้งหมด");
define("t_previous_day","วันก่อน");
define("t_job_date","งานวันที่");
define("t_transfer_to_account","โอนเงินเข้าบัญชี");
define("t_yes","ใช่");
define("t_no","ไม่ใช่");
define("t_load_data","โหลดข้อมูล");
define("t_THB","บาท");
define("t_extra_use_car","งานใช้รถเพิ่ม");
define("t_hour","ชั่วโมง");
define("t_close","ปิด");
define("t_total_allowance","รวมค่าเที่ยว เบี้ยเลี้ยง");
define("t_phone_fee","ค่าโทรศัพท์");
define("t_net_total_income","รายได้สุทธิ");
define("t_payment_account","บัญชีรายจ่าย");
define("t_all_transfer_job","งานส่งแขกทั้งหมด");
define("t_job_management","การจัดการงาน");
define("t_car_scheduling_time","ลำดับเวลาการเดินรถ");
define("t_parking_fee","ค่าจอด ค่าหัว");
define("t_chat_room","ห้องสนทนา");
define("t_back_to_previous_page","ย้อนกลับหน้าที่แล้ว");



?>