<?php  
define("t_n","");  
define("t_send_to_customer","Send guests");  
define("t_customer_history","Send guests record");  
define("t_job_received","Transfer job");  
define("t_tour_booking","Tour Booking");  
define("t_receipts","Income");  
define("t_expenses","expenses");  
define("t_my_account","my account");  
define("t_help_tools","help tools");  
define("t_all_jobs","All jobs");  
define("t_transfer_record","transfer record");  
define("t_province_you","province you are in");  
define("t_friends","Invite friend");  
define("t_maps","Maps");  
define("t_login_province","login to your province");  
define("t_login_another_province","login to another province");  
define("t_shopping","shopping");  
define("t_provinces","Other Province");  
define("t_guest_shopping","customer’s shopping");  
define("t_customer","transfer customer");  
define("t_yesterday","yesterday");  
define("t_today","today");  
define("t_no_guest_list","no guest list");  
define("t_transfer_customer","transfer customer");  
define("t_pick_up_place","Pick up place");  
define("t_exports","send to airport");  
define("t_private","private");  
define("t_pickup_customer","pick up customer");  
define("t_agents","agents");  
define("t_name_guest","customer name");  
define("t_phone","phone");  
define("t_voucher_number","voucher number");  
define("t_drop_place","Drop place");  
define("t_type_of_vehicle","Type of vehicle");  
define("t_arrive_drop_place","arrive at drop place");  
define("t_check_customer_name","check customer");  
define("t_check_vehicle","check vehicle");  
define("t_check_luggage","check luggage");  
define("t_photo","photo");  
define("t_time_taking_photo","time of taking photo");  
define("t_in_advance","in advance");  
define("t_no_job","no job");  
define("t_now","now");  
define("t_navigation","navigation");  
define("t_details","details");  
define("","distance 10.3km");  
define("","20 minutes");  
define("t_pay_deposit","please pay deposit");  
define("t_ok","ok");  
define("t_please_confirm_selection","please confirm your selection");  
define("t_not","not");  
define("t_select","select");  
define("t_jobs","jobs");  
define("t_total","total");  
define("t_total_expenses","total expenses");  
define("t_balances","balances");  
define("t_transfers","Transfers money");  
define("t_transfer_notice","transfer notice");  
define("t_transferred_account_details","transferred account details ");  
define("t_bank_name","bank name");  
define("t_account_number","account number");  
define("t_account_name","account name");  
define("t_your_balance","your balance");  
define("t_transfer_details","transfer details");  
define("t_transfer_banks","transfer banks");  
define("t_amount","amount");  
define("t_money_transfer_slip","upload bank slip");  
define("t_take_photos","take photo");  
define("t_cancel","cancel");  
define("t_no_photo_available","no photo available");  
define("t_unsubscribe","cancel sending guest");  
define("t_booking_number","booking number");  
define("t_reservation_information","booking details");  
define("t_car_driver_information","car and driver detail");  
define("t_check_in_information","Check in detail");  
define("t_place_of_delivery","arrived");  
define("t_reception","reception");  
define("t_income","income");  
define("t_parking_fee","Park fee");  
define("t_nationality","nationality");  
define("t_not_paid","not paid");  
define("t_documents","Document");  
define("t_pay_cash","pay cash");  
define("t_register","register");  
define("t_per_person","per person");  
define("t_Welcome_t-share","Welcome to T-Share");  
define("t_navigation_map","Navigation Map");  
define("t_flight","Flight");  
define("t_number","Number");  
define("t_customer_not_go","Customer not go");  
define("t_customer_no_register","Customer no register");  
define("t_wrong_selected_place","Wrong selected place");  
define("t_are_you_sure","Are you sure?");  
define("t_need_cancel_transfer","Need to cancel transfer");  
define("t_want_confirm_payment","Want to confirm payment");  
define("t_upload_the_document_picture","Please upload the document or picture");  
define("t_success","Success");  
define("t_process","Process");  
define("t_amend","Amend");  
define("t_confirm","Confirm");  
define("t_delivery_time","Delivery time");  
define("t_number_customers","Customers No.");  
define("t_adult","Adult");  
define("t_child","Child");  
define("t_infant","Infant");  
define("t_edit_data","Edit data");  
define("t_confirm_registration","Confirm registration");  
define("t_registration_failed","Registration failed");  
define("t_work_history","Work history");  
define("t_payment","Payment");  
define("t_status","Status");  
define("t_colleague","Colleague");  
define("t_today_job","Today job");  
define("t_add_new_job","Add new job");  
define("t_send","Send");  
define("t_remind","Remind");  
define("t_voice_dialing","Voice dialing");  
define("t_message","Message");  
define("t_car_information","Car information");  
define("t_add_new_car","Add new car");  
define("t_all_car","All car");  
define("t_income_details","Income details");  
define("t_receipt_of_parking_fee","Receipt of parking fee");  
define("t_withdrawal_record","Withdrawal record");  
define("t_bank_account","Bank account");  
define("t_personal_information","Personal information");  
define("t_important_data_file","Important data file");  
define("t_change_profile_picture","Change profile picture");  
define("t_contact_information","Contact Information");  
define("t_phone_number_the","Phone number");  
define("t_change_password","Change password");  
define("t_documents","Documents");  
define("t_work_information","Work information");  
define("t_missed_meal_fee","Allowance");  
define("t_overtime_pay","Salary & OT");  
define("t_phone_number","Phone Number");  
define("t_driver_phone_no","Driver phone no.");  
define("t_helpdesk","Helpdesk");  
define("t_find_hotel","Search hotel");  
define("t_check_flight","Check flight");  
define("t_language","Language");  
define("t_sign_out","Sign out");  
define("t_sign_out_successfully","Sign out successfully");  
define("t_started_waiting_for_customer","Started waiting for customer");  
define("t_go_with_king_power","Go with King Power‘s car");  
define("t_car_shifts","Car shifts");  
define("t_choose_car_shifts","Choose car shifts");  
define("t_send_back_location","Send back location");  
define("t_select_area","Select area");  
define("t_send_airport_shifts","Send to airport shifts");  
define("t_airport","Airport");  
define("t_home_page","Home");  
define("t_user_information","User Information");  
define("t_chat","Chat");  
define("t_financial_accounting","Financial Accounting");  
define("t_add_colleague","Add a colleague");  
define("t_manage_car","Manage the car");  
define("t_check_condition_car","Check the condition of the car.");  
define("t_inform_car_repair","Inform car repair");  
define("t_service_and_insurance","Service and Insurance");  
define("t_new_applier","New applier");  
define("t_all_colleagues","All colleagues");  
define("t_handle_task","Handle the task");  
define("t_open_for_business","Open for business");  
define("t_everyday","Everyday");  
define("t_work_remuneration","Remuneration");  
define("t_look_work_remuneration","View remuneration");  
define("t_location","Location");  
define("t_query","Query");  
define("t_marketing","Marketing");  
define("t_download","Download");  
define("t_bouchure","Bouchure");  
define("t_go_shopping","Go shopping");  
define("t_out_of_service","Out of service");  
define("t_select_region","Select region");  
define("t_place","Place");  
define("t_select_province","Select province");  
define("t_remaining_time","Remaining time");  
define("t_send_to_shopping","Send to shopping");  
define("t_duty_free","Duty free");  
define("t_all_transfer_job","All transfer job");  
define("t_nearest_location","Nearest location");  
define("t_price","Price");  
define("t_accept_order","Accept order");  
define("t_previous_day","Previous day");  
define("t_job_date","Job date");  
define("t_transfer_to_account","Transfer to account");  
define("t_yes","Yes");  
define("t_no","No");  
define("t_load_data","Load data");  
define("t_THB","THB");  
define("t_extra_use_car","Extra use car");  
define("t_hour","Hour");  
define("t_close","Close");  
define("t_total_allowance","Total allowance");  
define("t_phone_fee","Phone fee");  
define("t_net_total_income","Net total income");  
define("t_payment_account","Payment account");  
define("t_job_management","Job management");  
define("t_car_scheduling_time","Car scheduling time");  
define("t_chat_room","Chat room");  
define("t_back_to_previous_page","Back to previous page");  
define("t_guest_registration","Guest registration");  
define("t_income_statement","Income Statement");  
define("t_new_jobs","New Jobs");  
define("t_please_check","Please check");  
define("t_previous_day","Previous day");  
define("t_pass_re_in","Passenger Return Information");  
define("t_time_period","Time period");  
define("t_phuket_airport","Phuket Airport");  
define("t_termenal_finish","Has been sent to the destination");  
define("t_already_received","Already received");  
define("t_get_paid","You have already received money");  
define("t_on_the_car","On the car");  
define("t_profile","Profile");  
define("t_alert","Alert");  
define("t_take_photo_regis","Take photo registration form");  
define("t_please_take_photo_regis","Please take photo registration form");  
define("t_photo_passports","Photography passports guest");  
define("t_please_take_photo_drop_place","Please take photo of drop place");  
define("t_please_take_recep_photo","Please take receptionist photo");  
define("t_please_take_guest_regis","Please take a guest registration");  
define("t_take_photo_income_slip","Take photo income slip");  
define("t_passport","Passport");  
define("t_payment","Payment");  
define("t_open_ser","Open");  
define("t_open_now","Open now");  
define("t_calende_sunday","Sunday");  
define("t_calende_monday","Monday");  
define("t_calende_tuesday","Tuesday");  
define("t_calende_wednesday","Wednesday");  
define("t_calende_thursday","Thursday");  
define("t_calende_friday","Friday");  
define("t_calende_saturday","Saturday");  
define("t_show_detail","Show details");  
define("t_day","Day");  
define("t_register_18y_full_txt","Register must be 18 years or older.");  
define("t_china","China");  
define("t_person_fee","Person fee");  
define("t_minutes","Minutes");  
define("t_km","km");  
define("t_distance","Distance");  
define("t_time","time");  
define("t_office_hours","Office hours");  
define("t_advance_service","Advance service");  
define("t_open_over","Open 24 hours");  
define("t_close_time","Closing time");  
define("t_remuneration_type","Remuneration type");  
define("t_com_fee","Commitment");  
define("t_foreign","Other foreigner");  
define("t_timeout_service","Timeout service");  
define("t_person","Person");  
define("t_company","Company");  
define("t_driver","Driver");  
define("t_counter","Counter");  
define("t_member","Member");  
define("t_log_in","Signin");  
define("t_forgot_password","Forgot password");  
define("t_recovery_password","Password recovery");  
define("t_recovery_username","Recover User Name");  
define("t_use_phone_number","Use mobile phone number");  
define("t_please_enter_phone_number","Please enter the mobile number");  
define("t_please_enter_email","Please enter your email");  
define("t_user_name","Use username");  
define("t_please_enter_username","Please enter your username");  
define("t_register_member","Register member");  
define("t_username","Username");  
define("t_confirm_signout","You want to sign out?");  
define("t_password","Password");  
define("t_remember_me","Remember me");  
define("t_first_name","First name");  
define("t_last_name","Last name");  
define("t_nick_name","Nick name");  
define("t_current_address","Current address");  
define("t_province","Province");  
define("t_email","Email");  
define("t_not_mandatory","Not mandatory");  
define("t_take_photo","Take a photo");  
define("t_save_data","Save data");  
define("t_send_password","Send password");  
define("t_open_time","Open time");  
define("t_contact","Contact");  
define("t_south_area","South");  
define("t_search_by_name","Search by name");  
define("t_search_by_place","Search by place");  
define("t_calende","January");  
define("t_calende","February");  
define("t_calende","March");  
define("t_calende","April");  
define("t_calende","May");  
define("t_calende","June");  
define("t_calende","July");  
define("t_calende","August");  
define("t_calende","September");  
define("t_calende","October");  
define("t_calende","November");  
define("t_calende","December");  
define("t_calende","January");  
define("t_calende","February");  
define("t_calende","March");  
define("t_calende","April");  
define("t_calende","May");  
define("t_calende","June");  
define("t_calende","July");  
define("t_calende","August");  
define("t_calende","September");  
define("t_calende","October");  
define("t_calende","November");  
define("t_calende","December");  
define("t_calende","Sunday");  
define("t_calende","Monday");  
define("t_calende","Tuesday");  
define("t_calende","Wednesday");  
define("t_calende","Thursday");  
define("t_calende","Friday");  
define("t_calende","Saturday");  
define("t_date","Date");  
define("t_all","All");  
define("t_time_to_place","Time to place");  
define("t_delete","Delete");  
define("t_select_car_brand","Select a car brand");  
define("t_car_brand","Car brand");  
define("t_model_year_manufacture","Model / Year");  
define("t_choose_color","Choose a color");  
define("t_black","Black");  
define("t_yellow","Yellow");  
define("t_green","Green");  
define("t_red","Red");  
define("t_gray","Gray");  
define("t_bronce_gold","Bronze Gold");  
define("t_silver","Silver");  
define("t_car_registration_number","License plate");  
define("t_license_plate_color","License plate color");  
define("t_choose_license_plate_color","Choose a license plate color");  
define("t_take_picture_inside_car","Take a picture inside the car");  
define("t_reset","Reset");  
define("t_correct_information","Correct information");  
define("t_save_succeed","Save succeed");  
define("t_press_button_close","Press the button to close!");  
define("t_select_a_vehicle_type","Select a vehicle type");  
define("t_car_coloring","Car color");  
define("t_region","Region");  
define("t_please_take_pictures_car_side	","Please take pictures car side	");  
define("t_cancelled","Cancel");  
define("t_error","Error");  
define("t_white","White");  
define("t_please_take_pictures_front_car","Please take pictures in front of car");  
define("t_select_car_brand","Select car brand");  
define("t_please_enter_car_registration_number.","Please enter the car registration number.");  
define("t_please_take_pictures_front_car","Please take pictures in front of car");  
define("t_please_take_pictures_car_side","Please take pictures car side");  
define("t_please_take_picture_inside_car","Please take a picture inside the car");  
define("t_type","Type");  
define("t_deletess","Delete");  
define("t_open","Open");  
define("t_category","Category");  
define("t_address","Address");  
define("t_latitude","Latitude");  
define("t_longitude","Longitude");  
define("t_link_maps","Link maps");  
define("t_recommend_friend","QR CODE recommend to a friend");  
define("t_recommended_driver","Recommended to the driver");  
define("t_please_select_province","Please Select Province");  
define("t_no_products_your_province","No products in your province");  
define("t_kings_power _phuket","Kings Power (Phuket)");  
define("t_end_of_service","End of service");  
define("t_bus","Bus");  
define("t_van","Van");  
define("t_saloon","Saloon");  
define("t_edit_car_info","Edit car info");  
define("t_add_car","Add car");  
define("t_ancel_commonly_used","Deprecated");  
define("t_disable","Disable");  
define("t_brand","Brand");  
define("t_model","Model");  
define("t_use_regularly","Use regularly");  
define("t_cancel_often_used","Cancel often used");  
define("t_want_to_use_regularly","Want to use regularly");  
define("t_cancel_use","Cancel use");  
define("t_edit","Edit");  
define("t_month","Month");  
define("t_buddhist_calendar","B.E.");  
define("t_shopping","Shopping");  
define("t_bank","Bank");  
define("t_bank_branch","Bank branch");  
define("t_bank_account_information","Bank information");  
define("t_name_last_name_thai","Name - last name (Thai)");  
define("t_name_last_name_english","Name - last name (English)");  
define("t_identity_card_number","Identity card number");  
define("t_driver_license_number","Driver's license number");  
define("t_emergency_telephone_numbers","Emergency phone No.");  
define("t_user_info","User Info");  
define("t_identity_card","Identity card");  
define("t_driver_license","Driver's license");  
define("t_upload_file","Upload file");  
define("t_income_sort","Income sort");  
define("t_need_to_open","Need to open");  
define("t_district","District");  
define("t_select_district","Select district");  
define("t_search","Search");  
define("t_wrong_links","Wrong links");  
define("t_select_compensation_sort","Select compensation sort");  
define("t_VAT","VAT");  
define("t_have_VAT","Have VAT");  
define("t_pay_comission","Pay comission");  
define("t_customer_go_back","Customer go back");  
define("t_VAT_refund","VAT refund");  
define("t_VAT_can_refund_to_customer","VAT can refund to customer");  
define("t_default","Default");  
define("t_show_business_time","Show business time");  
define("t_open_daily","Open daily");  
define("t_open_24_hr","Open 24 hrs.");  
define("t_additional_time","Additional time");  
define("t_logo","Logo");  
define("t_select_picture","Select picture");  
define("t_select_brochure","Select brochure");  
define("t_please_fill_with_thai","Please fill with thai");  
define("t_please_fill_in_address","Please fill in address");  
define("t_please_fill_in_phont_no","Please fill in phone no.");  
define("t_add_document","Add document");  
define("t_select_document_type","Select document type");  
define("t_have_document_expire_date ","Have document expire date ");  
define("t_date_of_issue_expire","Date of issue-expire");  
define("t_to","To");  
define("t_files","Files");  
define("t_please_select_document_type","Please select document type");  
define("t_upload_file_success","Upload file success");  
define("t_province_log_in","Province log in");  
define("t_please_select_region","Please select region");  
define("t_apply_new_colleague","Apply new colleague");  
define("t_new_shopping_customer","New shopping customer");  
define("t_new_shopping_customer","Need to confirm register");  
define("t_need_to_cancel","Need to cancel");  
define("t_new","New");  
define("t_booking_no","Booking no.");  
define("t_boarding_time","Boarding time");  
define("t_name_last_name","Name - Last name");  
define("t_check_detail","Check detail");  
define("t_reject","Reject");  
define("t_enable","Enable");  
define("t_using","Using");  
define("t_need_to_enable","Need to enable");  
define("t_edit_car","Edit car");  
define("t_SUV","SUV");  
define("t_tuk_tuk","Tuk Tuk");  
define("t_mini_bus","Minibus");  
define("t_other","Other");  
define("t_set_up_car","Set up car");  
define("t_regular_car","Regular car");  
define("t_cancel_car","Cancel car");  
define("t_number_of_using_car","Number of using car");  
define("t_not_have_car","Not have car");  
define("t_car","Car");  
define("t_total_revenue","Total Revenue");  
define("t_enable_number","Enable number");  
define("t_no_enable_nationality","No enable nationality");  
define("t_user","User");  
define("t_number_of_people","Number of people");  
define("t_from","From");  
define("t_update","Update");  
define("t_update_price","Update price");  
define("t_please_select_initial_number_of_people.","Please select initial number of people.");  
define("t_please_select_end_number_people","Please select end number of people.");  
define("t_please_fill_in_price","Please fill in price.");  
define("t_show_all_price","Show all price");  
define("t_show_price_by_nationality","Show price by nationality");  
define("t_set_up_standard_price","Set up standard price");  
define("t_you_did_not_have_bank_account","You did not have bank account");  
define("t_add_new_bank_account","Add new bank account");  
define("t_please_select_bank","Please select bank");  
define("t_please_fill_in_bank_account_name","Please fill in bank account name");  
define("t_please_fill_in_bank_branch","Please fill in bank branch");  
define("t_please_fill_in_bank_account_number","Please fill in bank account number");  
define("t_save_personal_info_was_successed","Save personal info was successed");  
define("t_save_personal_info_was_failed","Save personal info was failed");  
define("t_please_fill_in_password","Please fill in password");  
define("t_please_fill_in_nickname","Please fill in nickname");  
define("t_error","error");  
define("t_public_bus_info","Public bus info");  
define("t_take_photo_ID_card","Take photo ID card");  
define("t_take_photo_driver_license","Take photo driver license");  
define("t_vehicle_registration","Vehicle registration");  
define("t_number","Number");  
define("t_vehicle_insurance","Vehicle insurance");  
define("t_insurance_company","Insurance company");  
define("t_insurance_number","Insurance number");  
define("t_take_photo_insurance","Take photo insurance");  
define("t_please_fill_in_driver_license_number","Please fill in driver license number");  
define("t_please_fill_in_driver_license_expire","Please fill in driver license expire");  
define("t_please_take_photo_driver_license","Please take photo driver license");  
define("t_please_select_u_address","Please select your area");  
define("t_please_take_photo","Please take a picture of yourself");  
define("t_please_u_pv","Please select your province");  
define("t_view_job_date","View job form date");  
define("t_please_select_hour","Please select hour");  
define("t_please_select_minute","Please select minute");  
define("t_pease_select_car","Please select your car");  
define("t_please_select_num_adult","Please select number of adults");  
define("t_please_select_remuneration","Please select remuneration");  
define("t_please_select_num_adult","Please select number of adult");  
define("t_please_select_num_child","Please select number of child");  
define("t_select_num_adult","Select number of adults");  
define("t_select_num_child","Select number of child");  
define("t_your_car_infor","Your car information");  
define("t_arrival_time","Ａrrival time");  
define("t_get_paid_type","Get paid");  
define("t_get_cash","Get cash");  
define("t_no_bank_acc","No bank account");  
define("t_back_previous","Back previous");  
define("t_not_verify_u_pv","Could not verify your province");  
define("t_call","Call");  
define("t_view_passport","View passport");  
define("t_hiden","Hide");  
define("t_show","Show");  
define("t_dv_name","Driver name");  
define("t_receptionist","Receptionist");  
define("t_history","History");  
define("t_pay_on","Paid date");  
define("t_paid","Paid");  
define("t_no_history","No history");  
define("t_pending","Waiting for processing");  
define("t_amount","Amount");  
define("t_confirm_or_receipt","Confirm of receipt");  
define("t_no_file_upload","No file upload");  
define("t_cause","Cause");  
define("t_guest_agent","Guest agent");  
define("t_photo","Photo");  
define("t_select_your_car","Choose your car");  
define("t_want_get_job","Want to get this booking !");  
define("t_his_transfer","History transfer");  
define("t_car_request","Car request");  
define("t_capacity","Capacity");  
define("t_use_car","Used car");  
define("t_take_pic_guest","Take a picture of guest name");  
define("t_no_guests","No guests");  
define("t_manage","Manage");  
define("t_transfer_his","Transfer record");  
define("t_complete_job","Complete");  
define("t_year","year");  
define("t_u_balance","your balance");  
define("t_job_confirmation","Job confirmation");  
define("t_booking","Booking");  
 ?> 