<?php

define("t_send_to_customer","Send customer");
define("t_customer_history","Send customer record");
define("t_job_received","Transfer job");
define("t_tour_booking","Tour Booking");
define("t_receipts","Income");
define("t_expenses","Expenses");
define("t_my_account","My account");
define("t_help_tools","Help tools");
define("t_all_jobs","All jobs");
define("t_transfer_record","Transfer record");
define("t_province_you","Province you are in");
define("t_friends","Invite friend");
define("t_maps","Maps");
define("t_login_phuket","Login to your province");
define("t_login_another_province","Login to another province");
define("t_shopping","Shopping");
define("t_provinces","Provinces");
define("t_guest_shopping","Customer’s shopping");
define("t_customer","Transfer customer");
define("t_yesterday","Yesterday");
define("t_today","Today");
define("t_no_guest_list","No guest list");
define("t_pick_up_place","Pick up place");
define("t_agents","Agents");
define("t_private","Private");
define("t_exports","Send to airport");
define("t_customer_name","Customer name");
define("t_phone","Phone");
define("t_voucher_number","Voucher number");
define("t_drop_place","Drop place");
define("t_type_of_vehicle","Type of vehicle");
define("t_arrive_drop_place","Arrive at drop place");
define("t_check_customer_name","Check customer name");
define("t_check_vehicle","Check vehicle");
define("t_check_luggage","Check luggage");
define("t_photo","Choto");
define("t_time_taking_photo","Time of taking photo");
define("t_in_advance","In advance");
define("t_no_job","No job");
define("t_now","Now");
define("t_navigation","Navigation");
define("t_details","Details");
define("t_distance","Distance");
define("t_km","km");
define("t_minutes","Minutes");
define("t_pay_deposit","Please pay deposit");
define("t_ok","Ok");
define("t_please_confirm_selection","Please confirm your selection");
define("t__not","Not");
define("t_select","Select");
define("t_jobs","Jobs");
define("t_total","Total");
define("t_total_expenses","Total expenses");
define("t_balances","Balances");
define("t_transfers","Transfers money");
define("t_transfer_notice","Transfer notice");
define("t_transferred_account_details","Transferred account details");
define("t_bank_name","bank name");
define("t_account_number","Account number");
define("t_account_name","Account name");
define("t_your_balance","Your balance");
define("t_transfer_details","Transfer details");
define("t_transfer_banks","	Transfer banks");
define("t_amount","Amount");
define("t_money_transfer_slip","Upload bank slip");
define("t_take_photos","Take photo");
define("t_cancel","Cancel");
define("t_no_photo_available","No photo available");
define("t_unsubscribe","cancel Sending customer");
define("t_booking_number","Booking number");
define("t_reservation_information","Booking details");
define("t_car_driver_information","Car and driver detail");
define("t_check_in_information","Check in detail");
define("t_place_of_delivery","Arrived");
define("t_reception","	Reception");
define("t_income","	Income");
define("t_parking fee","Parking fee");
define("t_nationality","Nationality");
define("t_not_paid","Not paid");
define("t_documents","Documents");
define("t_bouns","Personal expense");
define("t_pay_cash","Pay cash");
define("t_register","Register");
define("t_per_person","Per person"); 
define("t_time","Time"); 
define("t_home","Home page");
define("t_pick_up_customer","Pick up place"); 
 


define("t_Welcome_t-share","Welcome to T-Share"); 
define("t_navigation_map","Navigation Map"); 
define("t_flight","Flight"); 
define("t_number","Number"); 
define("t_customer_not_go","Customer not go"); 
define("t_customer_no_register","Customer no register"); 
define("t_wrong_selected_+place","Wrong selected place"); 
define("t_are_you_sure","Are you sure?"); 
define("t_need_cancel_transfer","Need to cancel transfer"); 
define("t_want_confirm_payment","Want to confirm payment"); 
define("t_upload_the_document_picture","Please upload the document or picture"); 
define("t_success","Success"); 
define("t_process","Process"); 
define("t_amend","Amend"); 
define("t_confirm","Confirm"); 
define("t_delivery_time","Delivery time"); 
define("t_number_customers","Number of customers"); 
define("t_adult","Adult"); 
define("t_child","Child"); 
define("t_infant","Infant"); 
define("t_edit_data","Edit data"); 
define("t_confirm_registration","Confirm registration"); 
define("t_registration_failed","Registration failed"); 
define("t_work_history","Work history"); 
define("t_payment","Payment"); 
define("t_status","Status"); 
define("t_colleague","Colleague"); 
define("t_today_job","Today job"); 
define("t_add_new_job","Add new job"); 
define("t_send","Send"); 
define("t_remind","Remind"); 
define("t_voice_dialing","Voice dialing"); 
define("t_message","Message"); 
define("t_car_information","Car information"); 
define("t_add_new_car","Add new car"); 
define("t_all_car","All car"); 
define("t_income_details","Income details"); 
define("t_receipt_of_parking_fee","Receipt of parking fee"); 
define("t_withdrawal_record","Withdrawal record"); 
define("t_bank_account","Bank account"); 
define("t_personal_information","Personal information"); 
define("t_important_data_file","Important data file"); 
define("t_change_profile_picture","Change profile picture"); 
define("t_contact_information","Contact Information"); 
define("t_phone_number_the","Phone number"); 
define("t_change_password","Change password"); 
define("t_documents","Documents"); 
define("t_work_information","Work information"); 
define("t_missed_meal_fee","Missed meal fee"); 
define("t_overtime_pay","Overtime pay"); 
define("t_phone_number","Phone Number"); 
define("t_driver_phone_no","Driver phone no."); 
define("t_helpdesk","Helpdesk"); 
define("t_find_hotel","Find hotel"); 
define("t_check_flight","Check flight"); 
define("t_language","Language"); 
define("t_sign_out","Sign out"); 
define("t_sign_out_successfully","Sign out successfully"); 
define("t_started_waiting_for_customer","Started waiting for customer"); 
define("t_go_with_king_power","ไGo with King Power‘s car"); 
define("t_car_shifts","Car shifts"); 
define("t_choose_car_shifts","Choose car shifts"); 
define("t_send_back_location","Send back location"); 
define("t_select_area","Select area"); 
define("t_send_airport_shifts","Send to airport shifts"); 
define("t_airport","Airport");

define("t_user_information","User Information");
define("t_chat","Chat");
define("t_financial_accounting","Financial Accounting");
define("t_add_colleague","Add a colleague");
define("t_manage_car","Manage the car");
define("t_check_condition_car.","Check the condition of the car.");
define("t_inform_car_repair","Inform car repair");
define("t_service_and_insurance","Service and Insurance");
define("t_new_applier","New applier");
define("t_all_colleagues","All colleagues");
define("t_handle_task","Handle the task");
define("t_open_for_business","Open for business");
define("t_everyday","Everyday");
define("t_work_remuneration","Work remuneration");
define("t_look_work_remuneration","Look at work remuneration");
define("t_location","Location");
define("t_query","Query");
define("t_marketing","Marketing");
define("t_download","Download");
define("t_bouchure","Bouchure");
define("t_go_shopping","Go shopping");
define("t_out_of_service","Out of service");
define("t_select_region","Select region");
define("t_place","Place");
define("t_select_province","Select province");
define("t_remaining_time","Remaining time");
define("t_send_to_shopping","Send to shopping");
define("t_duty_free","Duty free");
define("t_all_transfer_job","All transfer job");
define("t_nearest_location","Nearest location");
define("t_price","Price");
define("t_acept_order","Acept order");
define("t_all_transfer_job","All transfer job");
define("t_previous_day","Previous day");
define("t_job_date","Job date");
define("t_transfer_to_account","Transfer to account");
define("t_yes","Yes");
define("t_no","No");
define("t_load_data","Load data");
define("t_THB","THB");
define("t_extra_use_car","Extra use car");
define("t_hour","Hour");
define("t_close","Close");
define("t_total_allowance","Total allowance");
define("t_phone_fee","Phone fee");
define("t_net_total_income","Net total income");
define("t_payment_account","Payment account");
define("t_all_transfer_job","All transfer job");
define("t_job_management","Job management");
define("t_car_scheduling_time","Car scheduling time");
define("t_parking_fee","Parking fee");
define("t_chat_room","Chat room");
define("t_back_to_previous_page","Back to previous page");

?>